name: my-portfolio CI/CD pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-build:
    name: Build, and Deploy
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        if: success()
        run: npx vercel --token ${{ secrets.VERCEL_CICD_TOKEN }} --prod --yes
